## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

# TODO: remove this once HeaderREPLs is registered
before_script:
  - julia -e 'using Pkg;
              Pkg.clone("https://github.com/timholy/HeaderREPLs.jl")'

after_script:  # TODO: change to after_success once https://github.com/JuliaLang/julia/issues/28306 is fixed
  # push coverage results to Codecov
  - julia -e 'using Pkg, Rebugger; cd(joinpath(pathof(Rebugger), "..", "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # Update the documentation
  - julia -e 'using Pkg; Pkg.add("Documenter")'
  - julia -e 'ENV["DOCUMENTER_DEBUG"] = "true"; cd(joinpath(pathof(Rebugger), "..", "..")); include(joinpath("docs", "make.jl"))'
